#!/usr/bin/env python3.7

import string
import secrets

alphabet = string.ascii_letters + string.digits + string.punctuation
# Avoid things that cause problems when copypasta'd into bash.
alphabet = alphabet.replace('"', '').replace('!', '').replace('\\', '').replace('$', '').replace('`', '')
password = ''.join(secrets.choice(alphabet) for i in range(64))

with open('server/rcon.cfg', 'w') as f:
    f.write('// Generated by generate-rcon-password.py.\n')
    f.write(f'rcon_password "{password}"\n')

print(password)
